[package]
name = "resvg_wrapper"
version = "0.1.0"
edition = "2021"
authors = ["Kwiksher <support@kwiksher.com>"]
description = "Rust wrapper for resvg used in Solar2D Graphics Extensions"

[lib]
name = "resvg_wrapper"
crate-type = ["staticlib"]

[dependencies]
resvg = "0.28.0"
usvg = "0.28.0"
tiny-skia = "0.8.3"

[build-dependencies]
cbindgen = "0.24.3"
